apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - port: {{ .Values.service.port }}
    name: api
    targetPort: hdb-api